steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', '${_IMAGE_NAME}:$REVISION_ID', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        [[ "$BRANCH_NAME" == "master" ]] && /builder/kubectl.bash set image deployment kickoff nginx-front=gcr.io/rndcloud-codefest-wrike-tech/kickoff:$REVISION_ID || echo "skipping . . ."
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=codefest'
substitutions:
  _IMAGE_NAME: 'gcr.io/rndcloud-codefest-wrike-tech/kickoff'
images: ['gcr.io/rndcloud-codefest-wrike-tech/kickoff']
